### ISSUE TITLE
Error: Dataset folder not found on disk in demo_e2s2

### ISSUE THREAD

**Issue by amiltonwong** [nightrome/matconvnet-calvin#1]
Hi, @nightrome ,

I had followed the steps and compiled them successfully.
However, when I run "demo_e2s2()", it prompts me the following error. It seems the SiftFlowDataset dataset is missing. Could you also list the steps on preparing SiftFlowDataset dataset in order to run the demo successfully.   Many thanks!!
# 

demo_e2s2()
Error using SiftFlowDataset (line 35)
Error: Dataset folder not found on disk!

Error in demo_e2s2 (line 12)
dataset = SiftFlowDataset(); % Requires global folders to be set first
#

**Comment by nightrome** [comment]
It's at https://github.com/nightrome/matconvnet-calvin/blob/master/matconvnet-calvin/matlab/misc/SiftFlowDataset.m. Did you run setup()? The folder should be on your path already.

**Comment by amiltonwong** [comment]
Hi, @nightrome ,

Thanks for your reply and updated commit. I passed "dataset = SiftFlowDataset();". Now, I encounter another one, still couldn't pass "demo_e2s2":

# 

run demo_e2s2()
Warning: Cell element 1 differs!
Warning: Field path differs!
Warning: Cell element 1 differs!
Warning: Field dataset differs!
Error using e2s2_wrapper_SiftFlow (line 127)
Assertion failed.

Error in demo_e2s2 (line 27)
e2s2_wrapper_SiftFlow();

# 

Any suggestion to fix this problem?  THX~

**Comment by nightrome** [comment]
Okay. Just delete the broken contents of data/Features.

**Comment by nightrome** [comment]
There also seems to be a problem with VGG-16 pretrained on beta20 of MatConvNet. I will let you know in the next few days if I find a solution.

**Comment by nightrome** [comment]
@amiltonwong Sorry for the delay. Please check out the new release 0.4 ( https://github.com/nightrome/matconvnet-calvin/releases/tag/0.4 ). On my machine it produces good results in all 3 demos.

**Comment by amiltonwong** [comment]
@nightrome ,
Thank you very much for your kind help. 
Now, the training process is running :)
BTW, how long is the estimated training time? How long did it take for your hardware configuration? My system uses one GPU TITAN.

**Comment by nightrome** [comment]
Just added that info to the readme ( https://github.com/nightrome/matconvnet-calvin ). It's 10h for 10 epochs on SIFT Flow with VGG-16 and a single Titan X, which should be the minimum.

**Comment by amiltonwong** [comment]
Thanks! Got it ~
