### ISSUE TITLE
Windows-related error: Error file reading in FRCN

### ISSUE THREAD

**Issue by Addhi86** [nightrome/matconvnet-calvin#11]
Hello,

While running the code 'demo_frcn.m',  i am getting error:

>  In setupFastRcnnRegions (line 23)
>   In demo_frcn (line 20) 
> Error using textread (line 165)
> File not found.

`trainIms = textread(sprintf(DATAopts.imgsetpath, trainName), '%s'); %#ok<DTXTRD>`  I have checked the variables `DATAopts.imgsetpath` the path is correct. Then I couldn't understand why it is not reading the text file.

**Comment by nightrome** [comment]
Hi.
could you tell me the values of the following?
- `DATAopts.imgsetpath` (possibly anonymized)
- `trainName`

Alternatively run `exist(sprintf(DATAopts.imgsetpath, trainName), 'file')` to see whether the file actually exists (2 indicates it exists, 0 it doesn't).

**Comment by Addhi86** [comment]
Te values are:

`DATAopts.imgsetpath: C:\Users\AD\Downloads\matconvnet-calvin-master\matconvnet-calvin-master\data\Datasets\VOC2010/VOCdevkit/VOC2010/ImageSets/Main/%s.txt`
trainName: train

And the answer is 7 if i check the exist

**Comment by nightrome** [comment]
I think the problem is that you are one Windows. I guess mixing / and \ does not work very well and therefore Matlab thinks that this is a folder, not a file. You can try replacing all those slashes (`strrep(str, '/', '\')`), but I can't guarantee this will work everywhere in the VOC code :(.
