### ISSUE TITLE
Multi-GPU support for end-to-end semantic segmentation training

### ISSUE THREAD

**Issue by ice-pice** [nightrome/matconvnet-calvin#13]
Hi,

I want to train the end-to-end semantic segmentation network and i run `demo_e2s2_full`.
The run, however is limited to using 1 gpu as in <a href="https://github.com/nightrome/matconvnet-calvin/blob/master/matconvnet-calvin/examples/e2s2/e2s2_wrapper_SiftFlow_full.m#L17">this line</a> of your code.
I want the experiment to utilize multiple GPUs so I modify the line to `gpus = [1,2];` and simultaneously remove <a href="https://github.com/nightrome/matconvnet-calvin/blob/master/matconvnet-calvin/matlab/%40CalvinNN/init.m#L49">this assertion</a>.
The run is followed by this error:
```
Error using gpuDevice (line 26)
The input argument must be a positive integer or [].
```
Also, `SelectIdleGpu()` returns 1 gpu index, whereas my machine has 4.
```
>> SelectIdleGpu()
ans =
     4
```

I am fairly new to matconvnet, please let me know how to make the code support multi-GPU, if possible.

**Comment by nightrome** [comment]
Hi,

unfortunately multi-GPU training is not supported. So the assertion makes sense.
Regarding `SelectIdleGpu()` [1] it would be good if you could debug that for me.
Specifically try to run `gpuDeviceCount` and see if Matlab even detects more than one GPU.

[1] [https://github.com/nightrome/matconvnet-calvin/blob/master/matconvnet-calvin/examples/frcn/misc/SelectIdleGpu.m](https://github.com/nightrome/matconvnet-calvin/blob/master/matconvnet-calvin/examples/frcn/misc/SelectIdleGpu.m)

**Comment by ice-pice** [comment]
`gpuDeviceCount` returns a value of 4.
But <a href="https://github.com/nightrome/matconvnet-calvin/blob/master/matconvnet-calvin/examples/frcn/misc/SelectIdleGpu.m#L29">this line</a> makes it end the function and return the first GPU index.

Can you give more information about multi-gpu support of your code? I need to run this method on bigger datasets and it is very slow with 1 GPU. Thanks!

**Comment by nightrome** [comment]
Okay, so `gpuDeviceCount` works. I think you misunderstood what `SelectIdleGpu()` does (it isn't very well documented). It simply returns the *first* GPU that uses less than a certain amount of memory.

If you really want to code multi-gpu support you would have to tackle the `processEpoch()` [1] function. It is actually a modified version of Matconvnet's `processEpoch()` [2], which supports multiple GPUs. However we found for a much older version of MatConvNet that the speedup was small and that there were several bugs in it.

Alternatively try our `demo_e2s2_fast` script which should already train 4x faster with only a slight decrease in segmentation performance.

[1] [https://github.com/nightrome/matconvnet-calvin/blob/master/matconvnet-calvin/matlab/@CalvinNN/processEpoch.m](https://github.com/nightrome/matconvnet-calvin/blob/master/matconvnet-calvin/matlab/@CalvinNN/processEpoch.m)
[2] https://github.com/vlfeat/matconvnet/blob/master/examples/cnn_train.m#L226
