### ISSUE TITLE
Invalid CUDA device id: 2

### ISSUE THREAD

**Issue by ghost** [nightrome/matconvnet-calvin#14]
Hi, I am testing demo_fcn on ubuntu 16.04 with 'GeForce GT 730'. The following error happened when I ran demo_fcn. Has anyone encountered this before or know a way to workaround? Thanks.

```
 Error using gpuDevice (line 26)
Invalid CUDA device id: 2. Select a device id from the range 1:1.
 
 Error in CalvinNN/init (line 52)
     gpuDevice(nnOpts.gpus);
 
 Error in CalvinNN (line 30)
             obj.init(nnOpts);
 
 Error in FCNNN (line 9)
             obj = obj@CalvinNN(net, imdb, nnOpts);
 
 Error in fcnTrainGeneric (line 117)
 nnClass = FCNNN(netPath, imdbFcn, nnOpts);
 
 Error in demo_fcn (line 24)
 fcnTrainGeneric('expNameAppend', expNameAppend);
```

**Comment by nightrome** [comment]
Hi, you are right, the default GPU was set to be the second, which obviously only works on systems with multiple GPUs. I have changed fcnTrainGeneric.m now. Just run `git pull` (no need to recompile).
