### ISSUE TITLE
Binary Segmentation Problem

### ISSUE THREAD

**Issue by physics-programmer** [nightrome/matconvnet-calvin#15]
Hi, 
First of all, thanks for publishing this work.
I'v tried to use your code for numClasses = 1;
Imdb contains RGB inputs and masks in mat format that are binary mask taking 0 or 1 values.

I get this log : 

> fcnTrainGeneric('expNameAppend', 'testBinarySegmentation');
> Converting test AlexNet-style network to train FCN (1x1 convolutions, loss, etc.)...
> Starting train epoch: 1
> train: epoch 01:   1/ 61: 0.2 Hz (0.2 Hz) accuracy: 1.000 1.000 1.000 objective: 0.000
> train: epoch 01:   2/ 61: 0.2 Hz (0.2 Hz) accuracy: 1.000 1.000 1.000 objective: 0.000
> train: epoch 01:   3/ 61: 0.2 Hz (0.2 Hz) accuracy: 1.000 1.000 1.000 objective: 0.000

As you can see, accuracy = [1,1,1] and obj  = 0.
So network cannot train with this bug.

**Comment by nightrome** [comment]
Hi,
I think you will have to set numClasses = 2 and the mask has to take values 1 and 2 (Matlab-style indexing).

**Comment by physics-programmer** [comment]
Hi, thank you for your quick response.
It's working now, but accuracy is a vector of 3 values : 

> train: epoch 01:   1/ 61: 0.2 Hz (0.2 Hz) accuracy: 0.381 0.500 0.191 objective: 0.693
> train: epoch 01:   2/ 61: 0.2 Hz (0.2 Hz) accuracy: 0.491 0.493 0.323 objective: 0.806
> train: epoch 01:   3/ 61: 0.2 Hz (0.2 Hz) accuracy: 0.604 0.609 0.428 objective: 0.678

What are these 3 values ? is it "mean IU, mean pixel acc, and pixel acc" ?

**Comment by nightrome** [comment]
Almost. It's: pixelAcc: %5.2f, meanAcc: %5.2f, meanIU: %5.2f
https://github.com/nightrome/matconvnet-calvin/blob/master/matconvnet-calvin/examples/fcn/FCNNN.m#L458
