### ISSUE TITLE
Multi-path neural network

### ISSUE THREAD

**Issue by mafzal1** [nightrome/matconvnet-calvin#21]
Hi!
The architecture shown in the paper: 'Region-based semantic segmentation with end-to-end training' shows a multi-path neural network, each path having its own input and fc layers but merging at the region-to-pixel mapping point. Upon scanning the code for it, I cannot find how the two networks merge. I can only conclude that the pre-trained baseline model is already constructed as such. Is it possible that you could share the code for the baseline model? Or point to me the code where the networks merge?
Thank you.

**Comment by nightrome** [comment]
Hi,

referring to https://arxiv.org/pdf/1607.07671.pdf : 
- Fig. 2c: Don't be confused by the multiple region proposals (blue and red). This part is not a multi-path net. It's just one net applied to different proposals, like in Fast R-CNN.
- Fig. 3a (top): This could be considered multi-path. The fusion is simply via a fully connected layer over all neurons from both representations. The code can be found [here](https://github.com/nightrome/matconvnet-calvin/blob/42d7e80bac56741d39404b6646a0866c10aad021/matconvnet-calvin/examples/e2s2/E2S2NN.m#L30).

**Comment by mafzal1** [comment]
Hi,
With reference to Fig. 3a (top),
Could you point me to the code where the multi-path networks are being initialized? I am confused as to how the two paths are given their respective inputs and how are we training both pathways simultaneously?
Thank you!

**Comment by nightrome** [comment]
It is really just [those lines](https://github.com/nightrome/matconvnet-calvin/blob/42d7e80bac56741d39404b6646a0866c10aad021/matconvnet-calvin/examples/e2s2/E2S2NN.m#L30-L53). The weights are duplicated and MatConvNet automatically feeds two copies of the same input to the layer.
