### ISSUE TITLE
Selective search error resolution for windows

### ISSUE THREAD

**Issue by mafzal1** [nightrome/matconvnet-calvin#22]
Issue #9 and #18 both address the selective search issue but only for Mac OS and Ubuntu. How could I resolve the following error on windows:

Error using CountVisualWordsIndex (line 21)
First two input arguments should have the same 2D dimension

Error in BlobStructColourHist

Error in Image2HierarchicalGrouping (line 42)
[colourHist blobSizes] = BlobStructColourHist(blobIndIm, colourIm);

Error in demo (line 61)
[boxes blobIndIm blobBoxes hierarchy] = Image2HierarchicalGrouping(im, sigma, k, minSize, colorType, simFunctionHandles);

**Comment by nightrome** [comment]
Hi, unfortunately I haven't used Selective Search in 3 years and never on Windows. I suggest you try contacting the authors directly. Good luck.
