### ISSUE TITLE
Weights

### ISSUE THREAD

**Issue by mafzal1** [nightrome/matconvnet-calvin#23]
Hi, 
Referring to https://arxiv.org/pdf/1607.07671.pdf :
How does one figure whether the respective code is using tied weights or separate weights?
Thanks!

**Comment by nightrome** [comment]
Look at this parameter: https://github.com/nightrome/matconvnet-calvin/blob/42d7e80bac56741d39404b6646a0866c10aad021/matconvnet-calvin/examples/e2s2/e2s2_wrapper_SiftFlow_full.m#L21
