### ISSUE TITLE
error C3861: 'lround': identifier not found

### ISSUE THREAD

**Issue by nagdawi** [nightrome/matconvnet-calvin#4]
I use Matlab 2015a with windows 10.

> > vl_compilenn_calvin();
> > Building with 'Microsoft Windows SDK 7.1 (C++)'.
> > MEX completed successfully.
> > Building with 'Microsoft Windows SDK 7.1 (C++)'.
> > MEX completed successfully.
> > Building with 'Microsoft Windows SDK 7.1 (C++)'.
> > MEX completed successfully.
> > Building with 'Microsoft Windows SDK 7.1 (C++)'.
> > MEX completed successfully.
> > Building with 'Microsoft Windows SDK 7.1 (C++)'.
> > MEX completed successfully.
> > Building with 'Microsoft Windows SDK 7.1 (C++)'.
> > MEX completed successfully.
> > Building with 'Microsoft Windows SDK 7.1 (C++)'.
> > Error using mex
> > scoreBlobIoUs.cpp
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(155) : error C3861:
> > 'lround': identifier not found
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(156) : error C3861:
> > 'lround': identifier not found
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(157) : error C3861:
> > 'lround': identifier not found
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(158) : error C3861:
> > 'lround': identifier not found
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(161) : error C3861:
> > 'lround': identifier not found
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(162) : error C3861:
> > 'lround': identifier not found
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(163) : error C3861:
> > 'lround': identifier not found
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(164) : error C3861:
> > 'lround': identifier not found
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(173) : error C3861:
> > 'lround': identifier not found
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(174) : error C3861:
> > 'lround': identifier not found
> > 
> > Error in vl_compilenn_calvin (line 23)
> > mex(mexOpts{:}, fullfile(codeDir, 'misc', 'scoreBlobIoUs.cpp'));

any suggestion for this error??

**Comment by nightrome** [comment]
I'll look into it on Friday. Generally Visual Studio seems to be stricter
about mixing C and C++. For now try linux gcc instead.

**Comment by nightrome** [comment]
@nagdawi Please try the latest commit. It should fix that problem.

**Comment by nagdawi** [comment]
`

> > vl_compilenn_calvin();
> > Building with 'Microsoft Windows SDK 7.1 (C++)'.
> > MEX completed successfully.
> > Building with 'Microsoft Windows SDK 7.1 (C++)'.
> > MEX completed successfully.
> > Building with 'Microsoft Windows SDK 7.1 (C++)'.
> > MEX completed successfully.
> > Building with 'Microsoft Windows SDK 7.1 (C++)'.
> > MEX completed successfully.
> > Building with 'Microsoft Windows SDK 7.1 (C++)'.
> > MEX completed successfully.
> > Building with 'Microsoft Windows SDK 7.1 (C++)'.
> > MEX completed successfully.
> > Building with 'Microsoft Windows SDK 7.1 (C++)'.
> > Error using mex
> > scoreBlobIoUs.cpp
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(155) : error C2039: 'round'
> > : is not a member of 'std'
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(155) : error C3861: 'round':
> > identifier not found
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(156) : error C2039: 'round'
> > : is not a member of 'std'
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(156) : error C3861: 'round':
> > identifier not found
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(157) : error C2039: 'round'
> > : is not a member of 'std'
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(157) : error C3861: 'round':
> > identifier not found
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(158) : error C2039: 'round'
> > : is not a member of 'std'
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(158) : error C3861: 'round':
> > identifier not found
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(161) : error C2039: 'round'
> > : is not a member of 'std'
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(161) : error C3861: 'round':
> > identifier not found
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(162) : error C2039: 'round'
> > : is not a member of 'std'
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(162) : error C3861: 'round':
> > identifier not found
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(163) : error C2039: 'round'
> > : is not a member of 'std'
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(163) : error C3861: 'round':
> > identifier not found
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(164) : error C2039: 'round'
> > : is not a member of 'std'
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(164) : error C3861: 'round':
> > identifier not found
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(173) : error C2039: 'round'
> > : is not a member of 'std'
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(173) : error C3861: 'round':
> > identifier not found
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(174) : error C2039: 'round'
> > : is not a member of 'std'
> > C:\Users\Nagdawi\matconvnet-calvin\matconvnet-calvin\matlab\misc\scoreBlobIoUs.cpp(174) : error C3861: 'round':
> > identifier not found

Error in vl_compilenn_calvin (line 23)
mex(mexOpts{:}, fullfile(codeDir, 'misc', 'scoreBlobIoUs.cpp'));
`

**Comment by nagdawi** [comment]
sorry but this didn't solve the problem

**Comment by nightrome** [comment]
Sorry, but I can't test it here since I don't have Visual Studio.
What I have done now is to include a Matlab version of that file [1]. It's slower, but hopefully not too much.
So you can just get the latest version and ignore the above compilation errors because there is another file with that name.

[1] https://github.com/nightrome/matconvnet-calvin/blob/495af40cc1f0f4ef96378a396ec13b21c97b60b3/matconvnet-calvin/matlab/misc/scoreBlobIoUs.m
