### ISSUE TITLE
GPU-related error: No GPU available 

### ISSUE THREAD

**Issue by nagdawi** [nightrome/matconvnet-calvin#7]
```
Processing test img: 5105/5105
Warning: No GPU available 
> In SelectIdleGpu (line 33)
  In calvinNNDetection (line 45)
  In demo_frcn (line 23) 
Warning: Dataset not correctly divided 
> In ImdbMatbox (line 69)
  In ImdbDetectionFullSupervision (line 11)
  In setupImdbDetection (line 22)
  In calvinNNDetection (line 60)
  In demo_frcn (line 23) 
Error using gpuDevice (line 26)
The input argument must be a positive integer or [].

Error in CalvinNN/init (line 51)
    gpuDevice(nnOpts.gpus);

Error in CalvinNN (line 30)
            obj.init(nnOpts);

Error in calvinNNDetection (line 64)
calvinn = CalvinNN(net, imdb, nnOpts);

Error in demo_frcn (line 23)
calvinNNDetection();
 
>> 
```

**Comment by nightrome** [comment]
Try again with the latest update (run "git pull"). If it does not work please tell me. You can also workaround this the same way that we solved [https://github.com/nightrome/matconvnet-calvin/issues/6](https://github.com/nightrome/matconvnet-calvin/issues/6): Just set nnOpts.gpus = [] in [https://github.com/nightrome/matconvnet-calvin/blob/master/matconvnet-calvin/examples/frcn/calvinNNDetection.m#L45](https://github.com/nightrome/matconvnet-calvin/blob/master/matconvnet-calvin/examples/frcn/calvinNNDetection.m#L45).

But please note that Fast R-CNN (FRCN) is an object detection method, whereas E2S2 and FCN are semantic segmentation methods. So these are different tasks.

**Comment by nagdawi** [comment]
Thanks for your collaboration
